owner: luizQuizard
repo: upptime

sites:
  - name: API
    url: https://api.allnighter.ai/h
    expectedStatusCodes:
      - 200

  - name: API Application
    url: https://api.allnighter.ai/
    expectedStatusCodes:
      - 200

  - name: Ingestion Service
    url: https://quizardai--document.modal.run
    expectedStatusCodes:
      - 200
      - 405

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"

status-website:
  baseUrl: /upptime
  name: CourseGPT Status
  introTitle: "**CourseGPT** is currently"
  introMessage: Real-time status and incident history for CourseGPT services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
